

# **NumPy Practice Exercise**

Create **any 2D NumPy array** of your choice (at least **3 rows × 4 columns**) and complete the following tasks:




### Part 1 – Basic Information

1. Print the original array.
2. Print:

   * Shape
   * Number of dimensions (`ndim`)
   * Data type (`dtype`)
   * Total number of elements (`size`)

In [3]:
import numpy as np
arr2d= np.array([
[10,20,30,40],
[15,25,35,45],
[50,60,70,80]])

print(arr2d)
print("shape: " , arr2d.shape)
print("number of dimention :" , arr2d.ndim)
print("data type :" , arr2d.dtype)
print("array size = " , arr2d.size)



[[10 20 30 40]
 [15 25 35 45]
 [50 60 70 80]]
shape:  (3, 4)
number of dimention : 2
data type : int64
array size =  12


### Part 2 – Statistics

3. Calculate and print:

   * Sum of all elements
   * Mean
   * Maximum value
   * Minimum value

In [9]:
print("sum of all elements =" , arr2d.sum())
print("Mean =" , arr2d.mean())
print("maximum = ", arr2d.max())
print("minimum = ", arr2d.min())

sum of all elements = 480
Mean = 40.0
maximum =  80
minimum =  10


### Part 3 – Indexing & Slicing

4. Print:

   * The first row
   * The last row
   * The second column
   * A subarray of your choice

In [20]:
print("first row : ", arr2d[0])
print("last row : ", arr2d[-1])
print("second column : ", arr2d[:, 1])
print("subarray: ",arr2d[:3 ,:3])

first row :  [10 20 30 40]
last row :  [50 60 70 80]
second column :  [20 25 60]
subarray:  [[10 20 30]
 [15 25 35]
 [50 60 70]]


### Part 4 – Boolean Indexing

5. Print all values greater than the mean.
6. Replace all values greater than a number of your choice with `0`.

In [25]:
print("all values greater than mean : " , arr2d[arr2d> arr2d.mean()])
modified= arr2d.copy()
modified[modified>40]=0
print("Replace all values greater than a number of your choice with `0`\n",modified)

all values greater than mean :  [45 50 60 70 80]
Replace all values greater than a number of your choice with `0`
 [[10 20 30 40]
 [15 25 35  0]
 [ 0  0  0  0]]


### Part 6 – Axis Operations

10. Calculate:

* Sum of each column (`axis=0`)
* Mean of each row (`axis=1`)

In [28]:
print("column sum: " , arr2d.sum(axis=0))
print("mean of each row : " , arr2d.mean(axis=1))

column sum:  [ 75 105 135 165]
mean of each row :  [25. 30. 65.]


### Part 7 – Array Manipulation

11. Sort the array.
12. Reshape the array into a different valid shape.
13. Flatten the array into a 1D array.

In [34]:
print("sorted array : ")
print(
np.sort(arr2d.flatten()))
print("reshaped array:\n" , arr2d.reshape(4,3))

sorted array : 
[10 15 20 25 30 35 40 45 50 60 70 80]
reshaped array:
 [[10 20 30]
 [40 15 25]
 [35 45 50]
 [60 70 80]]
