## NumPy Array Manipulation

● Step 1: Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.


In [2]:
import numpy as np 

arr2d = np.arange(1,17).reshape(4,4)
print (arr2d)
print("shape:" , arr2d.shape)
print("Data type:" , arr2d.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
shape: (4, 4)
Data type: int64


● Step 2: Use slicing to extract the second column and the last row.


In [4]:
second_col= arr2d[: ,1]
last_row = arr2d[-1]
print("second columon =" , second_col)
print("last row =" , last_row)

second columon = [ 2  6 10 14]
last row = [13 14 15 16]


● Step 3: Use a boolean mask to select all values greater than the array's mean.


In [8]:
mean = arr2d.mean()
print(mean)
print("values grater than mean :", arr2d[arr2d > mean])

8.5
values grater than mean : [ 9 10 11 12 13 14 15 16]


● Step 4: Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.


In [13]:
arr = np.array([1 ,2 ,3 ,4])
result =arr2d +arr
print("original array :\n" ,arr2d)
print("row array :\n", arr)
print("added arrays :\n", result)

original array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row array :
 [1 2 3 4]
added arrays :
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]


# Manual verification:
First row:
[1,2,3,4] + [1,2,3,4]
= [2,4,6,8]
This matches result[0].