# Day 3 — Linear Algebra for ML  

## Step 1: Creating a Data Matrix

A dataset was represented as a NumPy matrix containing three samples.

Each row represents one sample, and each column represents one feature:
- Age
- Score
- Years of Experience

The matrix has a shape of `(3, 3)`, meaning it contains **3 samples** and **3 features**.

In [7]:
import numpy as np
data =np.array([[24 , 85 , 3],
               [23 , 80, 1],
               [22 , 79 , 2]
])
print(data)

[[24 85  3]
 [23 80  1]
 [22 79  2]]


## Step 2: Selecting One Sample Vector and Computing Dot Product with weights

The first sample was selected from the dataset to calculate its dot product with the weight vector.

This sample contains three feature values:
- Age
- Score
- Years of Experience

In [14]:
sample=data[0]
print(sampl)

[24 85  3]


### The Weight Vector

A weight vector was created to represent the importance of each feature.

The dot product is used to calculate the prediction by multiplying each feature by its corresponding weight and then summing the results.

**Calculation:**

(24 × 0.1) + (85 × 0.3) + (3 × 0.6)

= 2.4 + 25.5 + 1.8

= **29.7**

The result was then verified using NumPy's `np.dot()` function.

In [11]:
weight=np.array([0.1 , 0.3, 0.6])
result=np.dot(sampl,weight)
print(result)

29.7


The result obtained using `np.dot()` is **29.7**, which matches the manual calculation.

This confirms that the dot product was computed correctly.

## Step 3: Matrix Multiplication for All Samples

Matrix multiplication was used to calculate predictions for all samples at once.

Instead of calculating the dot product for each sample separately, the `@` operator performs the multiplication between the data matrix and the weight vector to produce predictions for all samples.

In [13]:
predictions = data @ weight

print(predictions)

[29.7 26.9 27.1]


## Step 4: Handling Shape Mismatch Error

In this step, we intentionally create a shape mismatch error by using a weight vector with the wrong number of elements.

The data matrix contains **3 features** for each sample, but the weight vector contains only **2 values**. This will cause matrix multiplication to fail.

In [17]:
weights2 = np.array([0.1, 0.3])

data @ weights2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

The error occurred because the dimensions of the two arrays are not compatible for matrix multiplication.

- `data.shape = (3, 3)` → 3 samples with 3 features each.
- `weights2.shape = (2,)` → only 2 weights.

Since each feature must have a corresponding weight, the weight vector must contain **3 values**.

### Fix

Create a weight vector with three elements:

```python
weights = np.array([0.1, 0.3, 0.5])

predictions = data @ weights
print(predictions)